### ISSUE TITLE
Implement UH CAS Login <BE01>

### ISSUE THREAD

**Issue by spyhi** [alloyteams/alloy#4]
To improve short-term security, Alloy accounts should use the University of Hawaii (UH) Central Authentication Service (CAS).

### Key Features:
- UH Login Button
- Links to the UH CAS
- Obtains user ID
- Obtains email
- Obtains first and last name (if possible)

**Note:** Investigate whether any other features can be obtained from the CAS.

**Comment by neilnthings** [comment]
I was able to get (CAS) UH login functionality working but I am unsure as to where username information is being stored.  I did not delete anything that was in the updated master.  I pushed a branch of the updated code under 'uhlogin_neil'.

I am not going to close this issue until I know where the UH login user information is being stored and I am able to retrieve it at will.

**Comment by reedv** [comment]
From looking at [this](https://github.com/atoy40/meteor-accounts-cas/blob/master/cas_server.js#L99) and using console.log() statements to look at user.services, user.services.cas, and user.service.cas.id in the validation function in startup/server/accounts.js, it seems that only the UH username is available. 

Also if you were not able to retrieve the username info, how were you able to get the app working since the accounts.js/onUserCreate() function requires the username to add to the custom Users collection. Just Slack me or in class. I was just here to post the first paragraph.

**Comment by neilnthings** [comment]
Troubleshooting why this issue is not moving to the 'done' column.
